branch-defaults:
  QA:
    environment: chatly--qa
  master:
    environment: Chatly-prod-env
  default:
    environment: chatly--qa
global:
  application_name: Chatly
  default_ec2_keyname: null
  default_platform: Docker 1.11.2
  default_region: us-east-1
  profile: eb-cli
  sc: git
